# Generated by Django 4.2.18 on 2025-01-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='captcha',
        ),
    ]
